#!/usr/bin/env python3
"""
Script that lists all databases in MongoDB.
"""
//Script that lists all databases in MongoDB.


from pymongo import MongoClient


def list_databases():
    """Connect to MongoDB and list all database names."""
    // Connect to MongoDB and list all database names.
    client = MongoClient()
    dbs = client.list_database_names()

    for db in dbs:
        print(db)


if __name__ == "__main__":
    list_databases()
